"""Added sales and stocks data

Revision ID: 17e2c694cbeb
Revises: 3e0eae0a4557
Create Date: 2025-03-27 13:47:24.914597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e2c694cbeb'
down_revision = '3e0eae0a4557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('comments')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales', sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('stocks', sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('stocks')
        batch_op.drop_column('sales')

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
