"""Changed the user and organization relationship to many-to-one

Revision ID: a89b1fabc311
Revises: e23fa869d01f
Create Date: 2025-03-10 02:55:27.448871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'a89b1fabc311'
down_revision = 'e23fa869d01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_organization')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', mssql.UNIQUEIDENTIFIER(), nullable=True))
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_id')

    op.create_table('user_organization',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('organization_id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='FK__user_orga__organ__6383C8BA'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK__user_orga__user___6477ECF3'),
    sa.PrimaryKeyConstraint('id', name='PK__user_org__3213E83FCAE684F5')
    )
    # ### end Alembic commands ###
