"""Updated content model

Revision ID: b43f9eddd7ec
Revises: 35c50c9b232d
Create Date: 2025-03-22 05:24:01.595578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'b43f9eddd7ec'
down_revision = '35c50c9b232d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=250), nullable=True),
    sa.Column('images', mssql.JSON(), nullable=True),
    sa.Column('organization_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('products')
    op.drop_table('campaigns')
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objective', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('audience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('media', mssql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tags', mssql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('product_id', mssql.UNIQUEIDENTIFIER(), nullable=True))
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])
        batch_op.drop_column('caption')
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('caption', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('tags')
        batch_op.drop_column('media')
        batch_op.drop_column('text')
        batch_op.drop_column('audience')
        batch_op.drop_column('objective')

    op.create_table('campaigns',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('goal', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('budget', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('target_audience', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('organization_id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='FK__campaigns__organ__02FC7413'),
    sa.PrimaryKeyConstraint('id', name='PK__campaign__3213E83F905C529C')
    )
    op.create_table('products',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('price', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=250, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('images', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('organization_id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='FK__products__organi__08B54D69'),
    sa.PrimaryKeyConstraint('id', name='PK__products__3213E83F6E04C1BE')
    )
    op.drop_table('product')
    # ### end Alembic commands ###
